apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: danydo1
    provider: github
    repository: app1-new
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: danydo1-app1-new
  namespace: jx
spec:
  httpCloneURL: https://github.com/danydo1/app1-new.git
  org: danydo1
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: app1-new
  scheduler:
    kind: ""
    name: in-repo
  url: https://github.com/danydo1/app1-new
